//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventID { get; set; }
        public string EventName { get; set; }
        public System.DateTime EventStartDate { get; set; }
        public System.DateTime EventEndDate { get; set; }
        public string EventPriceRange { get; set; }
        public string EventPromoter { get; set; }
        public string EventInfo { get; set; }
        public Nullable<int> VenueID { get; set; }
        public Nullable<int> GenreID { get; set; }
        public Nullable<int> PerformerID { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual Performer Performer { get; set; }
        public virtual Venue Venue { get; set; }
    }
}
